[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nmap <Space>t :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nmap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>
nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>
nmap <silent> <C-u><C-j> :<C-u>Denite line<CR>
nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
nmap <silent> <C-u><C-]> :<C-u>DeniteCursorWord grep<CR>
nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
nmap <silent> <C-u><C-r> :<C-u>Denite -resume<CR>
nmap <silent> <C-u>; :<C-u>Denite -resume -immediately -select=+1<CR>
nmap <silent> <C-u>- :<C-u>Denite -resume -immediately -select=-1<CR>
nmap <silent> <C-u><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
'''

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cohama/lexima.vim'


[[plugins]]
repo = 'kassio/neoterm'

hook_add = '''
" :Tnew の場合に挿入モードで開始する
let g:neoterm_autoinsert = 1

" :T {cmd} 実行時に画面スクロールをする
let g:neoterm_autoscroll = 1

" 縦分割する
" let g:neoterm_default_mod='vertical'
" 横分割する
let g:neoterm_default_mod='belowright'

" :Tnew 実行
nnoremap <silent> <C-e><C-t> :Tnew<CR>
" :Tnew 実行(縦分割)
nnoremap <silent> <C-e><C-v> :vertical Tnew<CR>
" 非ビジュアルモード
nnoremap <silent> <C-e><C-e> :TREPLSendLine<CR>
" ビジュアルモード
vnoremap <silent> <C-e><C-e> V:TREPLSendSelection<CR>
" ファイル送信
nnoremap <silent> <C-e><C-f> :TREPLSendFile<CR>
'''

[[plugin]]
repo = 'Shougo/deoplete.nvim'

hook_add = '''
call dein#add('roxma/nvim-yarp')
call dein#add('roxma/vim-hug-neovim-rpc')
let g:deoplete#enable_at_startup = 1
'''

