[[plugins]]
repo = 'Shougo/deoplete.nvim'

hook_add = '''
let g:deoplete#enable_at_startup   = 1
let g:deoplete#auto_complete_delay = 0
'''

hook_post_source = '''
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ deoplete#manual_complete()
'''

on_i = 1

